/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SimulatorRouteImport } from './routes/simulator'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PricesRouteImport } from './routes/prices'
import { Route as KycRouteImport } from './routes/kyc'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PoolsIndexRouteImport } from './routes/pools.index'
import { Route as PoolsPoolIdRouteImport } from './routes/pools.$poolId'

const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PricesRoute = PricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => rootRouteImport,
} as any)
const KycRoute = KycRouteImport.update({
  id: '/kyc',
  path: '/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsIndexRoute = PoolsIndexRouteImport.update({
  id: '/pools/',
  path: '/pools/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolsPoolIdRoute = PoolsPoolIdRouteImport.update({
  id: '/pools/$poolId',
  path: '/pools/$poolId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/prices': typeof PricesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools/': typeof PoolsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/prices': typeof PricesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools': typeof PoolsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/kyc': typeof KycRoute
  '/prices': typeof PricesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/simulator': typeof SimulatorRoute
  '/pools/$poolId': typeof PoolsPoolIdRoute
  '/pools/': typeof PoolsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/kyc'
    | '/prices'
    | '/reset-password'
    | '/simulator'
    | '/pools/$poolId'
    | '/pools/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/kyc'
    | '/prices'
    | '/reset-password'
    | '/simulator'
    | '/pools/$poolId'
    | '/pools'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/kyc'
    | '/prices'
    | '/reset-password'
    | '/simulator'
    | '/pools/$poolId'
    | '/pools/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  KycRoute: typeof KycRoute
  PricesRoute: typeof PricesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SimulatorRoute: typeof SimulatorRoute
  PoolsPoolIdRoute: typeof PoolsPoolIdRoute
  PoolsIndexRoute: typeof PoolsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prices': {
      id: '/prices'
      path: '/prices'
      fullPath: '/prices'
      preLoaderRoute: typeof PricesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kyc': {
      id: '/kyc'
      path: '/kyc'
      fullPath: '/kyc'
      preLoaderRoute: typeof KycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/': {
      id: '/pools/'
      path: '/pools'
      fullPath: '/pools/'
      preLoaderRoute: typeof PoolsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pools/$poolId': {
      id: '/pools/$poolId'
      path: '/pools/$poolId'
      fullPath: '/pools/$poolId'
      preLoaderRoute: typeof PoolsPoolIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  KycRoute: KycRoute,
  PricesRoute: PricesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SimulatorRoute: SimulatorRoute,
  PoolsPoolIdRoute: PoolsPoolIdRoute,
  PoolsIndexRoute: PoolsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
